// Package spec reads the W3C ARIA specification's own machine-readable role
// definitions out of the published HTML.
//
// # Why this exists
//
// aria/verify/testdata/aria.json is the single statement of the ARIA facts this
// framework depends on, and every guard in the two web exporters and the WASM
// runtime is held to it. It used to be hand-transcribed from the prose, which
// aria/verify/doc.go called out at the time as the weak link: a transcription
// can be wrong in exactly the way the prose it replaced could be wrong.
//
// It was. Generating the fixture from the spec for the first time changed five
// facts, none of which any test could have contradicted:
//
//	list.requiredOwned         held `group`. ARIA 1.2 requires only `listitem`
//	                           there — `group` is a listbox's allowance, not a
//	                           list's, and the two had been read as one.
//	radiogroup.orientation     held `horizontal`. ARIA 1.1 gave radiogroup an
//	                           implicit orientation and 1.2 removed it: the
//	                           role still takes aria-orientation, it just has
//	                           no default.
//	treegrid.orientation       held `vertical`, which no version of ARIA says.
//	nameProhibited             held `term` and `time`, both of which take a
//	                           name from the author in ARIA 1.2.
//
// The four that were wrong were all in near-miss rows — entries kept so a guard
// has something to argue with — which is why nothing failed. That is the point:
// an unchecked entry is prose again with braces around it, and the fix is not
// to check every entry by hand but to stop writing them by hand.
//
// # What it parses, and why regexes are enough
//
// The spec's role sections are generated by ReSpec from the source definitions,
// so the shape is machine-regular rather than editorial prose:
//
//	<section class="role notoc" id="toolbar">
//	  <div class="role-description">…</div>
//	  <table class="role-features">
//	    <tr><th class="role-parent-head">…      <td class="role-parent">…
//	    <tr><th class="role-properties-head">…  <td class="role-properties">…
//	    <tr><th class="role-inherited-head">…   <td class="role-inherited">…
//	    <tr><th class="role-namefrom-head">…    <td class="role-namefrom">author
//	    …
//
// Every fact this package wants is one of those cells, and every cell's content
// is a run of <a href="#aria-orientation"> or <a href="#option"> anchors. So the
// extraction is: find the section, find the cell, list the anchors. A full HTML
// parser would buy nothing here and would mean a dependency — golang.org/x/net
// is not in this module and this package is not worth adding it for.
//
// The one thing that is *not* a table cell is the implicit orientation, which
// the spec states as a sentence in the role's description:
//
//	Elements with the role <code>toolbar</code> have an implicit
//	<a href="#aria-orientation"><code>aria-orientation</code></a> value of
//	<code>horizontal</code>.
//
// Nine roles carry that sentence and its wording is identical in all nine, so it
// is read with a regex like everything else. Parse checks the count it found and
// fails rather than returning a fixture that quietly lost the orientations — see
// the sanity floors at the bottom of Parse.
//
// # Nothing here runs during verification
//
// This package is a library and aria/gen is a command; neither is on the path of
// `go test ./...`. The spec HTML is a 1.4MB download that is deliberately not
// committed, and aria/verify's conformance test skips when it is absent — the
// same stance ios/verify takes toward a missing iPhoneOS SDK and android/verify
// toward a missing Kotlin compiler. See aria/fetch.sh.
package spec

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// Role is one role's facts, as the spec states them.
//
// Deliberately not everything a role definition holds: no superclass chain, no
// related concepts, no required context. Those are real facts and nothing in
// this repository is held to them, and a field nobody checks is the thing this
// package exists to stop producing.
type Role struct {
	// Attributes are the aria-* attributes the role supports, inherits or
	// requires, with the ones it explicitly prohibits removed. Sorted.
	//
	// The three sources are unioned because ARIA's own guards do not
	// distinguish them: an author may write aria-selected on an `option`
	// (required), on a `row` (supported) and aria-disabled on either
	// (inherited), and "may this attribute appear on this role" has one
	// answer. Required is the source that matters most here and is the
	// easiest to miss — aria-selected on `option`, aria-level on `heading`
	// and aria-valuenow on every range role are all *required* properties
	// and appear in no other cell.
	Attributes []string

	// Orientation is the role's implicit aria-orientation value, or "" for a
	// role that has none. A role can support the attribute and have no
	// implicit value — `radiogroup` is exactly that in ARIA 1.2 — so this
	// being empty is not the same as the attribute being out of scope.
	Orientation string

	// RequiredOwned are the roles the spec's Required Owned Elements row
	// names, flattened. Sorted.
	//
	// Flattened because the cell can hold a path: a listbox's row reads
	// "group → option", meaning an option inside a group counts. Every
	// consumer here asks "is X an allowed child role of Y", which the flat
	// set answers and the path does not answer any better.
	RequiredOwned []string

	// NameProhibited is whether ARIA forbids an accessible name on the role.
	// The premise of the RoleGroup fallback both web exporters supply.
	NameProhibited bool
}

// Doc is every role section the spec publishes, keyed by role name.
type Doc map[string]Role

var (
	// A role section's opening tag. The class is "role notoc" today; matched
	// on the prefix so a class-list edit does not silently drop every role.
	sectionOpen = regexp.MustCompile(`<section class="role[^"]*" id="([a-z-]+)">`)
	// Section nesting: a role's description can hold <section> of its own, so
	// the closing tag is found by counting rather than by the first match.
	sectionTag = regexp.MustCompile(`</?section\b`)
	// An aria-* attribute reference inside a feature cell.
	attrRef = regexp.MustCompile(`href="#(aria-[a-z]+)"`)
	// A role reference inside a feature cell. The class is required: role
	// names and attribute names share the anchor namespace, and a cell can
	// mention both.
	roleRef = regexp.MustCompile(`href="#([a-z]+)" class="role-reference"`)
	// The implicit-orientation sentence. `(?s)` because the anchor markup
	// wraps across lines in the published HTML.
	// Whitespace-tolerant at every join: the published HTML puts the whole
	// sentence on one line, and a reflow would otherwise turn nine implicit
	// orientations into none without changing a word.
	implicitOrientation = regexp.MustCompile(
		`(?s)implicit\s+<a href="#aria-orientation".*?\s+value of\s+<code>(\w+)</code>`)
	// "See synonym <role>". Two roles in the whole spec — `none` and
	// `presentation` — are mutual synonyms, and only one of the pair carries
	// a feature table. See resolveSynonyms.
	synonymRef = regexp.MustCompile(`synonym\s*<a href="#([a-z]+)"`)
	// The document's own version, off the ReSpec title heading:
	//
	//	<h1 id="title" class="title">Accessible Rich Internet Applications
	//	(WAI-ARIA) 1.2</h1>
	//
	// The <title> element carries the same string and either would do; the
	// heading is used because it is the one a reader opening the file sees,
	// and because a proxy or an archiving tool is far likelier to have
	// rewritten the <title> than the document body.
	specTitle = regexp.MustCompile(
		`<h1 id="title" class="title">[^<]*\(WAI-ARIA\)\s+([0-9]+\.[0-9]+)</h1>`)
)

// Version is the ARIA revision this package reads, and the one every fact in
// the committed fixture came from.
//
// # Why the parser refuses any other
//
// The download is not committed (aria/fetch.sh), so what is on a given
// machine's disk is whatever that machine fetched, whenever it fetched it —
// and W3C publishes each revision at its own URL that keeps working forever.
// A checkout holding an ARIA 1.1 copy regenerates a *different* fixture, and
// the conformance test would then report it as a fixture that disagrees with
// the specification. That reading is exactly backwards: the fixture is right
// and the download is stale, and the diff it prints (radiogroup's orientation,
// `term` and `time` under nameProhibited — the very facts 1.2 changed) names
// four true statements about 1.1 as if they were transcription errors.
//
// So the version is read off the document and checked before anything else is
// believed about it. Costing one regexp, it turns the confusing failure into
// the one-line one, and it is the only thing here that could: every other
// signal a stale copy gives — role count, cell markup, the orientation
// sentence — is *identical* across the two revisions, because the format did
// not change between them. Only the content did.
//
// LocalPath spells the number too, and derives it from here so a bump is one
// edit. aria/fetch.sh's URL is the third statement of it and cannot read a Go
// constant; aria/spec's own test holds the script to this value instead.
const Version = "1.2"

// SpecVersion reads the ARIA revision the document declares, or "" if it
// carries no ReSpec title heading at all.
//
// Exported because the failure it exists for is a *download* problem rather
// than a parse problem, and the difference is worth being able to report
// separately: Parse folds it into an error, and aria/verify's conformance test
// wants to say "your copy is 1.1, re-run the fetch" rather than "the fixture
// is wrong".
func SpecVersion(html string) string {
	m := specTitle.FindStringSubmatch(html)
	if m == nil {
		return ""
	}
	return m[1]
}

// cellPattern builds the matcher for one <td class="role-X"> feature cell.
//
// Cached per class rather than compiled per role: Parse runs this against 94
// sections and there are five classes.
var cellPatterns = map[string]*regexp.Regexp{}

func cell(body, class string) string {
	re, ok := cellPatterns[class]
	if !ok {
		re = regexp.MustCompile(`(?s)<td class="` + class + `">(.*?)</td>`)
		cellPatterns[class] = re
	}
	m := re.FindStringSubmatch(body)
	if m == nil {
		return ""
	}
	return m[1]
}

// sections splits the document into role name → section body.
//
// The body is delimited by counting <section>/</section> from the opening tag
// rather than by finding the next </section>, because several role descriptions
// hold a nested <section> (a note, an example). Taking the first close would
// truncate those roles' feature tables — silently, since a truncated body parses
// to a role with no attributes rather than to an error.
func sections(html string) map[string]string {
	out := make(map[string]string)
	for _, m := range sectionOpen.FindAllStringSubmatchIndex(html, -1) {
		name := html[m[2]:m[3]]
		start := m[1]
		depth := 1
		for _, t := range sectionTag.FindAllStringIndex(html[start:], -1) {
			if html[start+t[0]+1] == '/' {
				depth--
			} else {
				depth++
			}
			if depth == 0 {
				out[name] = html[start : start+t[0]]
				break
			}
		}
	}
	return out
}

// uniqueSorted collapses a list of anchor targets to a sorted set.
func uniqueSorted(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	seen := make(map[string]bool, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}

func refs(re *regexp.Regexp, frag string) []string {
	var out []string
	for _, m := range re.FindAllStringSubmatch(frag, -1) {
		out = append(out, m[1])
	}
	return out
}

// Parse reads every role definition out of the published ARIA specification.
//
// html is the whole of https://www.w3.org/TR/wai-aria-1.2/ as fetched; see
// aria/fetch.sh. Nothing else about the document is required, and no ordering
// is assumed.
func Parse(html string) (Doc, error) {
	// Before the shape, the edition. A 1.1 copy parses perfectly and produces
	// a fixture that disagrees with the committed one on four facts — see
	// Version for why that failure has to be named here rather than left to
	// the diff downstream.
	//
	// An unreadable heading is an error too, and for the reason the floors
	// below are: this package's failures are all the quiet kind, and "the
	// document does not say what it is" is not a document to generate a
	// fixture from.
	if v := SpecVersion(html); v != Version {
		if v == "" {
			return nil, fmt.Errorf("no <h1 id=\"title\"> naming a WAI-ARIA version — "+
				"either this is not the ARIA specification, or ReSpec changed the "+
				"heading markup; expected version %s", Version)
		}
		return nil, fmt.Errorf("this is the WAI-ARIA %s specification and every fact "+
			"in the fixture comes from %s — the local copy is stale, and "+
			"regenerating from it would rewrite four true statements about %s as if "+
			"they were transcription errors.\n\nRe-run `sh aria/fetch.sh`", v,
			Version, Version)
	}

	doc, orientations := parseDoc(html)
	if len(doc) == 0 {
		return nil, fmt.Errorf("no <section class=\"role…\"> in the document — " +
			"either this is not the ARIA specification, or ReSpec changed the " +
			"markup this package reads; see spec.go for what it looks for")
	}

	// Sanity floors. Every failure this package can have is the quiet kind —
	// a markup change turns a cell into "" and the role reports no attributes,
	// which reads downstream as "ARIA does not allow that here" rather than as
	// a broken parse. So the shape of the *document* is asserted, not just the
	// shape of each cell.
	//
	// The numbers are floors well under what ARIA 1.2 actually publishes (94
	// roles, 9 implicit orientations), chosen so a later revision adding or
	// retiring a role does not fail the parse while a wholesale format change
	// does.
	//
	// They live here rather than in parseDoc so the parser can be exercised on
	// a handful of hand-written sections; a floor that made a five-role
	// document an error would leave the extraction itself untestable without
	// the 1.4MB download, which is the one thing these tests must not need.
	if len(doc) < 80 {
		return nil, fmt.Errorf("parsed only %d role sections, expected ~94 — "+
			"the section markup this package reads has probably changed", len(doc))
	}
	if orientations < 8 {
		return nil, fmt.Errorf("found only %d implicit aria-orientation sentences, "+
			"expected 9 — the wording implicitOrientation matches has probably "+
			"changed, and every role's default would silently become \"\"", orientations)
	}
	return doc, nil
}

// parseDoc is the extraction with no judgement about the document as a whole.
// Returns the roles and how many implicit-orientation sentences were found, the
// one fact Parse's floors need that the Doc does not carry.
func parseDoc(html string) (Doc, int) {
	bodies := sections(html)
	doc := make(Doc, len(bodies))
	synonyms := make(map[string]string)
	orientations := 0
	for name, body := range bodies {
		var r Role

		// Supported, inherited and required are one question; see Role.Attributes.
		attrs := refs(attrRef, cell(body, "role-properties"))
		attrs = append(attrs, refs(attrRef, cell(body, "role-inherited"))...)
		attrs = append(attrs, refs(attrRef, cell(body, "role-required-properties"))...)

		// Prohibited comes off the top. `caption` inherits aria-label from its
		// superclass and then forbids it, so the union alone would report an
		// attribute the spec explicitly refuses on that role.
		banned := make(map[string]bool)
		for _, a := range refs(attrRef, cell(body, "role-disallowed")) {
			banned[a] = true
		}
		kept := attrs[:0:0]
		for _, a := range attrs {
			if !banned[a] {
				kept = append(kept, a)
			}
		}
		r.Attributes = uniqueSorted(kept)

		r.RequiredOwned = uniqueSorted(refs(roleRef, cell(body, "role-mustcontain")))

		// The Name From cell is plain text ("author", "author, contents",
		// "prohibited", or an <abbr>n/a</abbr>), so it is stripped of markup
		// rather than scanned for anchors.
		nameFrom := strings.TrimSpace(stripTags(cell(body, "role-namefrom")))
		r.NameProhibited = nameFrom == "prohibited"

		if m := implicitOrientation.FindStringSubmatch(body); m != nil {
			r.Orientation = m[1]
			orientations++
		}

		// A section with no Name From row at all is a synonym stub. Recorded
		// now and resolved after the pass, since the target may not be parsed
		// yet.
		if nameFrom == "" {
			if m := synonymRef.FindStringSubmatch(body); m != nil {
				synonyms[name] = m[1]
			}
		}

		doc[name] = r
	}
	resolveSynonyms(doc, synonyms)
	return doc, orientations
}

// resolveSynonyms copies a role's facts onto the synonym that points at it.
//
// ARIA publishes `none` and `presentation` as synonyms of each other, and only
// `presentation` carries a feature table; `none`'s section is a sentence and a
// link. Without this, `none` parses as a role that allows no attributes and
// permits a name, which is the opposite of true.
//
// One hop, not a chain: the spec has exactly one synonym pair and a cycle
// between them, so following further would loop. A pair pointing at another
// stub leaves both as parsed, which a future revision would have to be read
// for anyway.
func resolveSynonyms(doc Doc, synonyms map[string]string) {
	for name, target := range synonyms {
		if t, ok := doc[target]; ok && len(t.Attributes) > 0 {
			doc[name] = t
		}
	}
}

// stripTags removes markup from a feature cell's text. Used only on Name From,
// whose value is a word rather than a list of links.
func stripTags(s string) string {
	var b strings.Builder
	depth := 0
	for _, r := range s {
		switch {
		case r == '<':
			depth++
		case r == '>':
			if depth > 0 {
				depth--
			}
		case depth == 0:
			b.WriteRune(r)
		}
	}
	return b.String()
}
