# The preconditions android/verify's JVM harness has, as a function of values.
#
# # Why this is not three inline `if`s
#
# It was, and every arm could only be reached by owning a machine with the
# fault. On a developer's Mac the `kotlinc` path ran and the two SKIP arms never
# did; in a bare container the SKIPs ran and the rest did not. A gate's failure
# mode is a swapped or misordered stance, and that is the mutation that leaves
# the pass green.
#
# Same move as wasm/verify/startup.mjs and aria/verify's localCopyGate, in
# shell: the decision takes its inputs as arguments and prints a verdict, so
# gate_test.sh can hand it every combination.
#
# # The ordering, which was the thing three inline guards could not state
#
# The old script asked `command -v kotlinc` FIRST and took that path, and only
# afterwards checked for a `java`. That order is wrong and the wrongness is
# invisible on every machine anyone has run it on: kotlinc is a JVM application,
# so on a machine with a kotlinc and no java it does not skip — it runs kotlinc,
# which fails, and `set -e` turns a missing optional toolchain into a red pass.
# Exactly the stance inversion this extraction exists to make reachable.
#
# So java is decided first, for both paths, and the order is asserted directly
# rather than being a property of how the arms happen to be written.
#
# # And why `go` is asked before either of them
#
# Not because a missing Go makes the java answer a guess — the three are
# independent `command -v` facts and nothing forces an order between Go and the
# JVM half. What forces it is what the script DOES between the questions.
#
# The harness runs Kotlin against a case table that `go run .` generates, and
# every arm below needs that table, so run.sh produced it before consulting this
# gate at all. On a machine with a JDK and no Go that line was reached, `go`
# was not found, and `set -e` turned a missing optional toolchain into a red
# pass — the SAME stance inversion the paragraph above is about, in the same
# file, two toolchains later. It was found by running the pass with a stripped
# PATH rather than by owning such a machine, which is the method this whole
# extraction exists to make available.
#
# Asking Go first restores the property that makes a gate a gate: nothing is
# executed before the verdict. The order is therefore not a preference about
# which remedy a reader hears first; it is where the first executable line sits.
#
# # The verdicts
#
# One line, `<action>:<why>`:
#
#	kotlinc:   compile with the kotlinc on PATH
#	cache:     assemble the compiler out of the gradle cache
#	skip:<why> this machine cannot answer the question
#
# There is no `fail`. A missing Go, JDK or Kotlin compiler is a fact about the
# MACHINE, and this script's promise is that it catches what this machine can
# catch — the same stance ios/verify takes toward a missing iPhoneOS SDK.

# jvm_harness_verdict <have-go: yes|no> <have-java: yes|no> <have-kotlinc: yes|no> <have-jars: yes|no>
jvm_harness_verdict() {
    if [ "$1" != "yes" ]; then
        echo "skip:no go on PATH, and the harness's case table is generated by gen.go; install Go to check it"
        return
    fi
    if [ "$2" != "yes" ]; then
        echo "skip:no java; install a JDK to check it"
        return
    fi
    if [ "$3" = "yes" ]; then
        echo "kotlinc:"
        return
    fi
    if [ "$4" != "yes" ]; then
        echo "skip:no kotlinc, and the gradle cache has no Kotlin compiler; run android/gradlew -p android :app:fetchKotlinCompiler once with a network to populate it, or install kotlinc"
        return
    fi
    echo "cache:"
}

# The preconditions android/verify's Kotlin SOURCE pass has, as a function of
# values. See sources.sh for what the pass does; this decides whether it can run.
#
# # Why this gate is separate from the one above
#
# They answer about different machines. jvm_harness_verdict is about executing
# two import-free Kotlin files on a JVM, and its whole toolchain is a compiler.
# This one is about type-checking Kotlin that imports Compose, the Android SDK,
# osmdroid and coil, which needs three more things — an Android SDK, a resolved
# compile classpath, and the Compose compiler plugin — each of which can be
# absent on a machine where the other pass runs perfectly.
#
# # The order, and why it is this order
#
# Each precondition is asked before the one whose answer its absence would make
# a guess:
#
#	java         gradle and the Kotlin compiler are both JVM applications. With
#	             no JDK neither can be run, so "the classpath did not resolve"
#	             and "no compiler in the cache" would both be true and neither
#	             would be the reader's problem.
#	sdk          the gradle task prints the platform jars from AGP's own
#	             bootClasspath, and AGP fails the whole task when it cannot find
#	             an SDK. Asked first, a missing SDK is reported as a missing SDK;
#	             asked after, it arrives as a gradle failure whose message is
#	             four lines of stack.
#	classpath    whether that gradle call actually produced one. The commonest
#	             "no" is not a broken build file but a cold cache: sources.sh
#	             asks --offline, so a machine that has never run a gradle build
#	             resolves nothing. That is the CI-shaped machine, and it is the
#	             one arm of this gate that a reader is likely to meet, so the
#	             sentence names the one online command that fixes it before the
#	             diagnostic that explains a genuinely broken resolution.
#	compiler     and only then the Kotlin side, which is the one precondition
#	             that is about the machine's Kotlin cache rather than its
#	             Android setup.
#
# # Why a missing Compose plugin is a skip and not a weaker run
#
# Without the plugin `@Composable` is an ordinary annotation with no meaning to
# the compiler, and this file compiles clean:
#
#	fun Bad() { Text("nope") }
#
# With it, two errors — a @Composable invoked outside a @Composable context is
# the single largest class of Compose-specific mistake, and the plugin is the
# only thing that knows the rule. A compile without it is a different, weaker
# check wearing the same OK, which is exactly the shape this repository's guards
# exist to refuse. So its absence is named rather than absorbed.
#
# The plugin also has to be the compiler's own version, which is why sources.sh
# asks the cache for it by version rather than taking the newest: they are
# published in lockstep and a mismatched pair fails inside the compiler.
#
# # The remedy sentences, which were checked and were wrong
#
# Both compiler skips used to name a task that does not fetch a compiler. This
# one said `:app:printVerifyClasspath`, which resolves the APP's compile
# classpath and contains no compiler at all; the harness gate above said
# `compileDebugKotlin`, which does pull one and needs libs/grmob.aar — the
# gomobile build this pass exists to not require. A reader who met either skip,
# ran what it said and tried again met the same skip.
#
# They name `:app:fetchKotlinCompiler` now, which was added for them: see
# android/app/build.gradle. Measured from an empty GRADLE_USER_HOME, that one
# task plus printVerifyClasspath is the whole of what these two passes need —
# no assembleDebug, no NDK, no gomobile.
#
# The lesson is the one this whole directory is about. A skip sentence is the
# only thing a reader on a machine that cannot run the pass ever sees, and it is
# the one part of a gate that no arm of gate_test.sh can check: the table proves
# the five sentences are DIFFERENT, and nothing proves any of them is true. That
# is a hole, and the only instrument for it is running the remedy on a machine
# that has the fault.

# kotlin_source_verdict <have-java> <have-sdk> <have-classpath> <have-compiler> <have-plugin>
kotlin_source_verdict() {
    if [ "$1" != "yes" ]; then
        echo "skip:no java; install a JDK to check it"
        return
    fi
    if [ "$2" != "yes" ]; then
        echo "skip:no Android SDK; export ANDROID_HOME, or write sdk.dir into android/local.properties"
        return
    fi
    if [ "$3" != "yes" ]; then
        echo "skip:gradle did not resolve a compile classpath — most often a cache this build has never filled, since sources.sh asks --offline; run android/gradlew -p android :app:printVerifyClasspath once with a network, then android/gradlew -p android :app:dependencies if it still will not"
        return
    fi
    if [ "$4" != "yes" ]; then
        echo "skip:the gradle cache has no Kotlin compiler; run android/gradlew -p android :app:fetchKotlinCompiler once with a network to populate it"
        return
    fi
    if [ "$5" != "yes" ]; then
        echo "skip:the gradle cache has no Compose compiler plugin at the Kotlin compiler's version, and without it a @Composable called from a plain function compiles clean"
        return
    fi
    echo "run:"
}
