// Command gen emits the JVM harness's case tables as Kotlin source (see
// run.sh): the picker menus, and the accessibility value ranges.
//
// Both tables have the same shape and exist for the same reason. A Kotlin file
// that imports nothing can be run on a plain JVM, so the two transliterations
// that would otherwise be checked by searching their own source for substrings
// — GrMobSelectMenu.kt and GrMobProgress.kt — are compared against the Go
// functions they transliterate instead.
//
// # Why source rather than JSON
//
// ios/verify hands its Swift harness a JSON transcript, because Swift has
// Decodable in the standard library and a struct with the right field names
// decodes itself. Kotlin's standard library has no JSON parser at all, and
// neither does the JDK — so a JSON transcript here would mean either a
// dependency (which is the thing this harness exists to avoid: it must run
// against whatever a `--offline` gradle cache happens to hold) or a
// hand-written parser in the harness, which is a second piece of untested code
// standing between the fixture and the thing under test.
//
// Emitting Kotlin removes both. The table crosses as literals the Kotlin
// compiler reads, and the only code in the harness is the comparison.
//
// What does not change is where the answers come from: Want is computed by
// core.SelectMenuSections (internal/menufixture), the same authority htmlout
// calls and the same table ios/verify and wasm/verify use. Nothing here is
// hand-transcribed, which is the whole point — a fixture written out twice
// proves only that one person made the same mistake twice.
package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/rohanthewiz/grmob/internal/canvasfixture"
	"github.com/rohanthewiz/grmob/internal/menufixture"
	"github.com/rohanthewiz/grmob/internal/rebasefixture"
	"github.com/rohanthewiz/grmob/internal/valuefixture"
)

// kstr renders a Go string as a Kotlin string literal.
//
// Kotlin interpolates '$' inside a double-quoted literal, so it is escaped
// alongside the backslash and the quote. None of the fixture's strings
// currently contains one; the escape is here because a fixture case is exactly
// the kind of thing someone extends with a hostile-looking heading — which is
// what htmlout's own escaping tests already do one directory over.
func kstr(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		`$`, `\$`,
		"\n", `\n`,
		"\t", `\t`,
	)
	return `"` + r.Replace(s) + `"`
}

func main() {
	var b strings.Builder

	// The same package as the file under test, so the harness calls
	// grMobMenuSections directly rather than through an import that would have
	// to be kept in step.
	b.WriteString(`package com.grmob.runtime

// GENERATED by android/verify/gen.go from internal/menufixture. Do not edit:
// it is written into a scratch directory at every run and never into the repo.
//
// Each case is an option list in the flat wire shape core.Select produces,
// paired with the menu core.SelectMenuSections says it decomposes into.

val menuCases: List<MenuCase> = listOf(
`)

	for _, c := range menufixture.Cases() {
		fmt.Fprintf(&b, "    MenuCase(\n        name = %s,\n        options = listOf(\n", kstr(c.Name))
		for _, o := range c.Options {
			b.WriteString("            mapOf(")
			// The wire keys, in a fixed order so the generated file is stable
			// across runs: Go's map iteration is deliberately randomised, and
			// a fixture that reordered itself every run would make any diff of
			// the generated source unreadable.
			first := true
			for _, k := range []string{"value", "label", "group", "disabled", "groupDisabled"} {
				v, ok := o[k]
				if !ok {
					continue
				}
				if !first {
					b.WriteString(", ")
				}
				first = false
				fmt.Fprintf(&b, "%s to %s", kstr(k), kstr(v))
			}
			b.WriteString("),\n")
		}
		b.WriteString("        ),\n        want = listOf(\n")
		for _, w := range c.Want {
			fmt.Fprintf(&b, "            WantSection(%s, %d, %t, listOf(\n",
				kstr(w.Heading), w.First, w.Disabled)
			for _, it := range w.Items {
				fmt.Fprintf(&b, "                WantItem(%d, %s, %s, %t),\n",
					it.Index, kstr(it.Value), kstr(it.Label), it.Disabled)
			}
			b.WriteString("            )),\n")
		}
		b.WriteString("        ),\n    ),\n")
	}

	b.WriteString(")\n")

	writeProgressCases(&b)
	writeCanvasCases(&b)
	writeRebaseCases(&b)
	os.Stdout.WriteString(b.String())
}

// writeRebaseCases emits the text-edit rebase table.
//
// The fourth Kotlin file that imports nothing: GrMobTextEdits.kt holds the
// ledger a focused field keeps, and rebaseEdit and rebaseCaret, which replay
// typing Go has not seen onto Go's rewrite. The rule runs on the host alone,
// so internal/rebasefixture states it in Go and supplies the answers, and
// ios/verify runs the Swift copy against the same table.
func writeRebaseCases(b *strings.Builder) {
	b.WriteString(`
// GENERATED by android/verify/gen.go from internal/rebasefixture.
//
// Each case is a rewrite arriving at a focused field (basis, local text,
// rewrite and the caret in the local text), paired with the text and caret
// Go's reference gives.

val rebaseCases: List<RebaseCase> = listOf(
`)
	for _, c := range rebasefixture.Cases() {
		fmt.Fprintf(b, "    RebaseCase(%s, %s, %s, %s, %d, %s, %d),\n",
			kstr(c.Name), kstr(c.Basis), kstr(c.Local), kstr(c.Rewrite), c.Caret,
			kstr(c.Want), c.WantCaret)
	}
	b.WriteString(")\n")
}

// writeProgressCases emits the accessibility-value table.
//
// The second thing this generator carries, and the second Kotlin file that
// imports nothing: core.ValueRange.Progress decides what three wire strings
// amount to, and GrMobProgress.kt transliterates it. The numbers cross as the
// strings a renderer's parser actually receives, so the parse is inside what
// is being compared rather than beside it.
//
// The reading crosses as its Go spelling (core.ProgressReading is a string
// type for exactly this) and Kotlin holds the same four literals, so the
// harness compares values rather than a mapping table that would itself need
// checking.
func writeProgressCases(b *strings.Builder) {
	b.WriteString(`
// GENERATED by android/verify/gen.go from internal/valuefixture.
//
// Each case is one core.ValueRange as it crosses the wire, paired with the
// reading core.ValueRange.Progress gives it.

val progressCases: List<ProgressCase> = listOf(
`)
	for _, c := range valuefixture.Cases() {
		w := valuefixture.Want(c)
		fmt.Fprintf(b, "    ProgressCase(%s, %s, %s, %s, %s, WantProgress(%s, %sf, %sf, %sf)),\n",
			kstr(c.Name), kstr(c.Range.Now), kstr(c.Range.Min), kstr(c.Range.Max),
			kstr(c.Range.Text), kstr(string(w.Reading)),
			knum(w.Now), knum(w.Min), knum(w.Max))
	}
	b.WriteString(")\n")
}

// writeCanvasCases emits the canvas geometry table.
//
// The third Kotlin file that imports nothing: GrMobCanvasGeometry.kt maps a
// viewBox onto the canvas's box and replays core's path opcodes, which is
// arithmetic SVG does for the web targets and nobody does for Android but that
// file. Go's answers come from core.CanvasMapping through
// internal/canvasfixture. Doubles, not Floats: the comparison is of the
// arithmetic, and a Float round trip would hide an off-by-a-bit mapping inside
// its own rounding.
func writeCanvasCases(b *strings.Builder) {
	b.WriteString(`
// GENERATED by android/verify/gen.go from internal/canvasfixture.
//
// Each case is a viewBox, a box, a scale and one path's wire opcodes, paired
// with the mapping and the drawing calls Go says they produce.

val canvasCases: List<CanvasCase> = listOf(
`)
	dlist := func(vs []float64) string {
		parts := make([]string, len(vs))
		for i, v := range vs {
			parts[i] = kdouble(v)
		}
		return "listOf<Double>(" + strings.Join(parts, ", ") + ")"
	}
	for _, c := range canvasfixture.Cases() {
		w := canvasfixture.WantFor(c)
		fmt.Fprintf(b, "    CanvasCase(%s, %s, %s, %s, %s, %t, %s, %s, %s, %s, %s, listOf(\n",
			kstr(c.Name), kdouble(c.VW), kdouble(c.VH), kdouble(c.BoxW), kdouble(c.BoxH), c.Stretch,
			dlist(c.Ops), kdouble(w.SX), kdouble(w.SY), kdouble(w.OX), kdouble(w.OY))
		for _, call := range w.Calls {
			fmt.Fprintf(b, "        CanvasCall(%s, %s),\n", kstr(call.Op), dlist(call.Args))
		}
		b.WriteString("    )),\n")
	}
	b.WriteString(")\n")
}

// kdouble renders a float64 as a Kotlin Double literal: always with a decimal
// point, since a bare "3" is an Int to Kotlin.
func kdouble(f float64) string {
	s := strconv.FormatFloat(f, 'f', -1, 64)
	if !strings.Contains(s, ".") {
		s += ".0"
	}
	return s
}

// knum renders a float64 as a Kotlin Float literal.
//
// 'f' with the shortest round-tripping precision, matching core.formatValue:
// %g would emit scientific notation past six digits, which Kotlin's own
// literal grammar accepts but which turns a byte counter's expectation into
// something no reader of the generated file can check by eye.
func knum(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}
