// Command gen emits the picker-menu case table as Kotlin source, for the JVM
// conformance harness next door (see run.sh).
//
// # Why source rather than JSON
//
// ios/verify hands its Swift harness a JSON transcript, because Swift has
// Decodable in the standard library and a struct with the right field names
// decodes itself. Kotlin's standard library has no JSON parser at all, and
// neither does the JDK — so a JSON transcript here would mean either a
// dependency (which is the thing this harness exists to avoid: it must run
// against whatever a `--offline` gradle cache happens to hold) or a
// hand-written parser in the harness, which is a second piece of untested code
// standing between the fixture and the thing under test.
//
// Emitting Kotlin removes both. The table crosses as literals the Kotlin
// compiler reads, and the only code in the harness is the comparison.
//
// What does not change is where the answers come from: Want is computed by
// core.SelectMenuSections (internal/menufixture), the same authority htmlout
// calls and the same table ios/verify and wasm/verify use. Nothing here is
// hand-transcribed, which is the whole point — a fixture written out twice
// proves only that one person made the same mistake twice.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/rohanthewiz/grmob/internal/menufixture"
)

// kstr renders a Go string as a Kotlin string literal.
//
// Kotlin interpolates '$' inside a double-quoted literal, so it is escaped
// alongside the backslash and the quote. None of the fixture's strings
// currently contains one; the escape is here because a fixture case is exactly
// the kind of thing someone extends with a hostile-looking heading — which is
// what htmlout's own escaping tests already do one directory over.
func kstr(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		`$`, `\$`,
		"\n", `\n`,
		"\t", `\t`,
	)
	return `"` + r.Replace(s) + `"`
}

func main() {
	var b strings.Builder

	// The same package as the file under test, so the harness calls
	// grMobMenuSections directly rather than through an import that would have
	// to be kept in step.
	b.WriteString(`package com.grmob.runtime

// GENERATED by android/verify/gen.go from internal/menufixture. Do not edit:
// it is written into a scratch directory at every run and never into the repo.
//
// Each case is an option list in the flat wire shape core.Select produces,
// paired with the menu core.SelectMenuSections says it decomposes into.

val menuCases: List<MenuCase> = listOf(
`)

	for _, c := range menufixture.Cases() {
		fmt.Fprintf(&b, "    MenuCase(\n        name = %s,\n        options = listOf(\n", kstr(c.Name))
		for _, o := range c.Options {
			b.WriteString("            mapOf(")
			// The wire keys, in a fixed order so the generated file is stable
			// across runs: Go's map iteration is deliberately randomised, and
			// a fixture that reordered itself every run would make any diff of
			// the generated source unreadable.
			first := true
			for _, k := range []string{"value", "label", "group", "disabled", "groupDisabled"} {
				v, ok := o[k]
				if !ok {
					continue
				}
				if !first {
					b.WriteString(", ")
				}
				first = false
				fmt.Fprintf(&b, "%s to %s", kstr(k), kstr(v))
			}
			b.WriteString("),\n")
		}
		b.WriteString("        ),\n        want = listOf(\n")
		for _, w := range c.Want {
			fmt.Fprintf(&b, "            WantSection(%s, %d, %t, listOf(\n",
				kstr(w.Heading), w.First, w.Disabled)
			for _, it := range w.Items {
				fmt.Fprintf(&b, "                WantItem(%d, %s, %s, %t),\n",
					it.Index, kstr(it.Value), kstr(it.Label), it.Disabled)
			}
			b.WriteString("            )),\n")
		}
		b.WriteString("        ),\n    ),\n")
	}

	b.WriteString(")\n")
	os.Stdout.WriteString(b.String())
}
